### ISSUE TITLE
Special characters' display

### ISSUE THREAD

**Issue by Participation-Trophy** [Pixelfck/ExanimaLore#4]
The icons used in the document can have inconsistent display across browsers if left up to them. It would be an improvement if it was ensured that the display would remain the same (provided font/svg). I've tried making a pull request with a custom font on my fork, but it seems like the main branch here is locked for a refactor.

If it helps, I've seen good icons from [Iconoir](https://iconoir.com/) which I used for the font. I can upload the font file or the svgs if it's convenient.

**Comment by Pixelfck** [comment]
Oh, yes, replacement SVG icons would be most welcome!

I just added support for svg icons (the copy icon; the icon itself might be improved upon), but if you could provide the svg icons, that would be brilliant!

**Comment by Participation-Trophy** [comment]
Here they are. I grabbed these from Iconoir and it has its license [here](https://github.com/iconoir-icons/iconoir/blob/main/LICENSE) (they just want a copy of their license on works). I think you just need to put it in a file in your projects with all the licenses and also the final output/html file (comment in the \<head>).
You may also want to grab the icons themselves in the site. They have configurable settings like varying the stroke width and more if you plan to alter the icons a bit. 
![long-arrow-down-right](https://github.com/Pixelfck/ExanimaLore/assets/132187033/69a014af-2f64-4a3d-80c9-fb5d01706f2b)
![long-arrow-right-down](https://github.com/Pixelfck/ExanimaLore/assets/132187033/f4e64456-d590-4060-a582-0f88babd51b1)
![x](https://github.com/Pixelfck/ExanimaLore/assets/132187033/831fdd9f-8e20-4b86-a731-e426d05417b4)
You can look them up on the site with their names: long-arrow-down-right, long-arrow-right-down, and x.

I slightly preferred the old copy icon, what happened to it? More importantly, the copy icon also shows up incorrectly as a gray square in my mobile browser. It works fine when I reduce the viewport width in my desktop though.

**Comment by Pixelfck** [comment]
Unfortunately, I can't accept licenced material, not even MIT.

**Comment by Participation-Trophy** [comment]
Oof, that's rough. A lot of the places where you get these icons and have a good collection is licensed one way or another. Is there a reason why you won't use them?

**Comment by Participation-Trophy** [comment]
About the svg icons scaling incorrectly in mobile, I think the problem is the same. Other browsers require the `-webkit-` prefix to work on the other attributes too. You could add them individually or consider using just the shorthand mask and -webkit-mask attribute.

I've tried to make a few of the svg icons myself, but other from the cross symbol, the arrows don't look good to me (too fat). Thoughts?
![iconDiagContinue](https://github.com/Pixelfck/ExanimaLore/assets/132187033/7063fa13-bedf-4b70-aeec-69999c8de830)
![iconDiagEnd](https://github.com/Pixelfck/ExanimaLore/assets/132187033/90c3852b-1e77-4f48-a1cf-eeeef63bd5b9)
![iconDiagNext](https://github.com/Pixelfck/ExanimaLore/assets/132187033/2f1270ef-2391-48df-b6d8-37d2875c242f)

**Comment by Pixelfck** [comment]
I think the arrows look good. They might look fat at this scale, but I think they will look just right at the `1em` size.

**Comment by Pixelfck** [comment]
Closes #12 #21

**Comment by Pixelfck** [comment]
Closes #12 #21
